### ISSUE TITLE
module declares its path as: github.com/ahmetb/go-linq/v3 but was required as: gopkg.in/ahmetb/go-linq.v3

### ISSUE THREAD

**Issue by mage1k99** [caddyserver/circuitbreaker#1]
```
go: github.com/caddyserver/circuitbreaker upgrade => v0.0.0-20200502164936-524f74b0eb0d
get "gopkg.in/ahmetb/go-linq.v3": found meta tag get.metaImport{Prefix:"gopkg.in/ahmetb/go-linq.v3", VCS:"git", RepoRoot:"https://gopkg.in/ahmetb/go-linq.v3"} at //gopkg.in/ahmetb/go-linq.v3?go-get=1
go get: github.com/caddyserver/circuitbreaker@v0.0.0-20200502164936-524f74b0eb0d requires
        gopkg.in/ahmetb/go-linq.v3@v3.1.0: parsing go.mod:
        module declares its path as: github.com/ahmetb/go-linq/v3
                but was required as: gopkg.in/ahmetb/go-linq.v3
2020/07/20 18:25:14 [FATAL] exit status 1

```
**module declares its path as: github.com/ahmetb/go-linq/v3
                but was required as: gopkg.in/ahmetb/go-linq.v3**

**Comment by mholt** [comment]
Looks like the import path changed: https://github.com/ahmetb/go-linq/issues/92

Want to make a patch, try it out, and submit a PR? :smiley:

**Comment by mage1k99** [comment]
I tried to build it after making changes to the import, I faced another issue `can't load package: package github.com/mailgun/holster: no Go files in $GOPATH/src/github.com/mailgun/holster`. [Issue mailgun/holster#72](https://github.com/mailgun/holster/issues/72)
